### ISSUE TITLE
BIG PROBLEM SMALL DICK(SENTEMON'S)

### ISSUE THREAD

**Issue by risknu** [sentemon/CSharpChallenges#2]
Sentemon5ick have big problem in code, but he have small problem(dick)
his small problem like art:
8==>
|-----|
0      0.9

**Comment by gmalanchuk** [comment]
https://github.com/sentemon/CSharpChallenges/assets/69295468/f022b849-3d20-4d8d-b3f7-425b27eefb8b

https://github.com/sentemon/CSharpChallenges/assets/69295468/eafa4de7-9f58-43db-901a-3ecc91538e0c

**Comment by gmalanchuk** [comment]
https://github.com/sentemon/CSharpChallenges/assets/69295468/b0089cbf-0923-43ca-8554-2b7e7fb1719d

**Comment by gmalanchuk** [comment]
https://github.com/sentemon/CSharpChallenges/assets/69295468/b4378b7e-a2d6-4249-8ed2-f59ab7791476
